apiVersion: apps/v1
kind: Deployment
metadata:
  name: myback
  labels:
    app: myback
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myback
  template:
    metadata:
      labels:
        app: myback
    spec:
      containers:
      - name: myback-container
        image: kube-back-example:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: DB_HOST
          value: mysql-service
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: myback-service
spec:
  type: NodePort
  selector:
    app: myback
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
    nodePort: 30001
