apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfront
  labels:
    app: myfront
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myfront
  template:
    metadata:
      labels:
        app: myfront
    spec:
      containers:
      - name: myfront-container
        image: kube-front-example:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "http://myback-service:3001/number"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"


---
apiVersion: v1
kind: Service
metadata:
  name: myfront-service
spec:
  type: NodePort
  selector:
    app: myfront
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
