apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: cm9vdF9wYXNzd29yZA== # Base64 'root_password'
  mysql-user: dXNy # Base64 'usr'
  mysql-password: aGVsbG8== # Base64 'pass'
  mysql-database: ZGI= # Base64 'db'
